language: node_js
sudo: false
node_js:
  - 0.10
before_script:
  - git config --global user.email "dev@carrotcreative.com"
  - git config --global user.name "Carrot Creative"
after_script:
  - istanbul cover _mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage
